server:
  host: "0.0.0.0"
  port: 8090
  name: "Slyth Server"
  description: "Welcome to the server!"
  max_players: 20

  admin:
    admin_password: "a3_W9_UiD432"
    all_players_admins: false

  tps_log_interval: 5

  chat:
    enable: true
    max_message_length: 64

game:
  map:
    width: 100
    height: 100
    food_perc: 2
  viewport:
    width: 100
    height: 75
    scale_factor: 1.0
  snake:
    default_length: 1
    min_length_fast_mode: 1
    default_mode:
      move_timeout: 0.1
      steal_chance: 0.005
    fast_mode:
      enable: true
      move_timeout: 0.05
      steal_chance: 0.1

logging:
  console_level: "debug"
  file: "server_logs/log.txt"
  file_level: "debug"
